'use strict';
(function(){
  var PAPER='#f5f1e8',INK='#0a0a0a',SIGNAL='#ff4d00';
  var MAXPTS=300,GRID_FINAL=128,GRID_ANIM=64;
  var PATTERNS=['moons','blobs','circles','xor'];
  var MODEL_LABEL={logreg:'LOGISTIC REGRESSION',svm:'SUPPORT VECTOR MACHINE',knn:'K-NEAREST NEIGHBORS',tree:'DECISION TREE'};
  var canvas=document.getElementById('field'),ctx=canvas.getContext('2d'),emptyEl=document.getElementById('empty');
  var W=0,H=0,dpr=1,points=[],cachedGrid=null,cachedN=GRID_FINAL,animToken=0,patternIdx=0,inited=false,rafPending=false;
  var state={algo:'knn',brush:0,params:{lr:0.8,knnK:7,treeDepth:5,svmKernel:'rbf',svmGamma:12,svmC:30}};

  function clamp01(v){return v<0?0:v>1?1:v;}
  function clampt(t){if(!isFinite(t))return 0.5;return t<0?0:t>1?1:t;}
  function dist(a,b){var dx=a.x-b.x,dy=a.y-b.y;return Math.sqrt(dx*dx+dy*dy);}
  function setText(id,t){var e=document.getElementById(id);if(e)e.textContent=t;}
  function randn(){var u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
  function clampP(v){return Math.max(0.06,Math.min(0.94,v));}

  function normalizeFit(raw){var minx=Infinity,maxx=-Infinity,miny=Infinity,maxy=-Infinity,i,p;for(i=0;i<raw.length;i++){p=raw[i];if(p.rx<minx)minx=p.rx;if(p.rx>maxx)maxx=p.rx;if(p.ry<miny)miny=p.ry;if(p.ry>maxy)maxy=p.ry;}var sx=(maxx-minx)||1,sy=(maxy-miny)||1,out=[];for(i=0;i<raw.length;i++){p=raw[i];out.push({x:0.12+0.76*(p.rx-minx)/sx,y:0.12+0.76*(p.ry-miny)/sy,label:p.label});}return out;}
  function genMoons(){var raw=[],c=22,nz=0.055,i,a;for(i=0;i<c;i++){a=Math.PI*i/(c-1);raw.push({rx:Math.cos(a)+randn()*nz,ry:Math.sin(a)+randn()*nz,label:0});raw.push({rx:1-Math.cos(a)+randn()*nz,ry:0.5-Math.sin(a)+randn()*nz,label:1});}return normalizeFit(raw);}
  function genBlobs(){var pts=[];function add(cx,cy,l,n){for(var i=0;i<n;i++)pts.push({x:clampP(cx+randn()*0.09),y:clampP(cy+randn()*0.09),label:l});}add(0.30,0.66,0,20);add(0.70,0.34,1,20);return pts;}
  function genCircles(){var pts=[],i,a,r;for(i=0;i<16;i++){a=Math.random()*6.283;r=Math.random()*0.13;pts.push({x:clampP(0.5+r*Math.cos(a)),y:clampP(0.5+r*Math.sin(a)),label:0});}for(i=0;i<28;i++){a=Math.random()*6.283;r=0.30+Math.random()*0.09;pts.push({x:clampP(0.5+r*Math.cos(a)),y:clampP(0.5+r*Math.sin(a)),label:1});}return pts;}
  function genXor(){var pts=[];function add(cx,cy,l){for(var i=0;i<10;i++)pts.push({x:clampP(cx+randn()*0.07),y:clampP(cy+randn()*0.07),label:l});}add(0.28,0.28,0);add(0.72,0.72,0);add(0.72,0.28,1);add(0.28,0.72,1);return pts;}
  function generate(name){return name==='moons'?genMoons():name==='blobs'?genBlobs():name==='circles'?genCircles():genXor();}

  function sigmoid(z){return 1/(1+Math.exp(-z));}
  function knnScorer(){var k=Math.min(state.params.knnK,points.length),pts=points;return function(x,y){var d=[],i,dx,dy;for(i=0;i<pts.length;i++){dx=pts[i].x-x;dy=pts[i].y-y;d.push([dx*dx+dy*dy,pts[i].label]);}d.sort(function(a,b){return a[0]-b[0];});var s=0;for(i=0;i<k;i++)s+=d[i][1]===1?1:-1;return s/k;};}
  function gini(n0,n1){var t=n0+n1;if(t===0)return 0;var p0=n0/t,p1=n1/t;return 1-p0*p0-p1*p1;}
  function buildTree(idx,depth,maxD){var n0=0,n1=0,i;for(i=0;i<idx.length;i++){if(points[idx[i]].label===1)n1++;else n0++;}var node={depth:depth,p1:idx.length?n1/idx.length:0.5,leaf:true};if(depth>=maxD||idx.length<2||n0===0||n1===0)return node;var parentG=gini(n0,n1),best=null,f,key,sorted,s,v1,v2,thr,l0,l1,t,r0,r1,g;for(f=0;f<2;f++){key=f===0?'x':'y';sorted=idx.slice().sort(function(a,b){return points[a][key]-points[b][key];});for(s=1;s<sorted.length;s++){v1=points[sorted[s-1]][key];v2=points[sorted[s]][key];if(v1===v2)continue;thr=(v1+v2)/2;l0=0;l1=0;for(t=0;t<s;t++){if(points[sorted[t]].label===1)l1++;else l0++;}r0=n0-l0;r1=n1-l1;g=((l0+l1)/idx.length)*gini(l0,l1)+((r0+r1)/idx.length)*gini(r0,r1);if(best===null||g<best.g)best={g:g,f:f,thr:thr};}}if(!best||best.g>=parentG-1e-9)return node;key=best.f===0?'x':'y';var L=[],R=[];for(i=0;i<idx.length;i++){if(points[idx[i]][key]<=best.thr)L.push(idx[i]);else R.push(idx[i]);}if(!L.length||!R.length)return node;node.leaf=false;node.f=best.f;node.thr=best.thr;node.left=buildTree(L,depth+1,maxD);node.right=buildTree(R,depth+1,maxD);return node;}
  function treeScorer(root,reveal){return function(x,y){var node=root;while(!node.leaf&&node.depth<reveal){node=((node.f===0?x:y)<=node.thr)?node.left:node.right;}return node.p1-0.5;};}
  function treeMaxDepth(n){return n.leaf?n.depth:Math.max(treeMaxDepth(n.left),treeMaxDepth(n.right));}
  function treeLeaves(n){return n.leaf?1:treeLeaves(n.left)+treeLeaves(n.right);}
  function logregScorer(w){return function(x,y){return w[0]+w[1]*x+w[2]*y;};}
  function logregEpoch(w,lr){var g0=0,g1=0,g2=0,i,p,z,pr,e,n=points.length;for(i=0;i<n;i++){p=points[i];z=w[0]+w[1]*p.x+w[2]*p.y;pr=sigmoid(z);e=pr-p.label;g0+=e;g1+=e*p.x;g2+=e*p.y;}w[0]-=lr*g0/n;w[1]-=lr*g1/n;w[2]-=lr*g2/n;}
  function logregLoss(w){var s=0,i,p,z,pr,n=points.length;for(i=0;i<n;i++){p=points[i];z=w[0]+w[1]*p.x+w[2]*p.y;pr=Math.min(1-1e-9,Math.max(1e-9,sigmoid(z)));s+=-(p.label*Math.log(pr)+(1-p.label)*Math.log(1-pr));}return s/n;}
  function svmKfun(){var g=state.params.svmGamma;if(state.params.svmKernel==='rbf')return function(a,b){var dx=a.x-b.x,dy=a.y-b.y;return Math.exp(-g*(dx*dx+dy*dy));};return function(a,b){return a.x*b.x+a.y*b.y+1;};}
  function svmStep(m,lambda,K,iters){var n=points.length,it,i,s,j,yj,yi;for(it=0;it<iters;it++){i=(Math.random()*n)|0;s=0;for(j=0;j<n;j++){if(m.alpha[j]!==0){yj=points[j].label===1?1:-1;s+=m.alpha[j]*yj*K(points[i],points[j]);}}s=s/(lambda*m.t);yi=points[i].label===1?1:-1;if(yi*s<1)m.alpha[i]++;m.t++;}}
  function svmScorer(m,lambda,K){var snap=m.alpha.slice(),t=m.t,pts=points.slice();return function(x,y){var s=0,q={x:x,y:y},j,yj;for(j=0;j<pts.length;j++){if(snap[j]!==0){yj=pts[j].label===1?1:-1;s+=snap[j]*yj*K(q,pts[j]);}}return s/(lambda*t);};}

  function vertexScores(gridN,scorer){var arr=new Float32Array((gridN+1)*(gridN+1)),idx=0,i,j,y;for(j=0;j<=gridN;j++){y=j/gridN;for(i=0;i<=gridN;i++){arr[idx++]=scorer(i/gridN,y);}}return arr;}
  var MS={0:[],15:[],1:[['L','T']],2:[['T','R']],3:[['L','R']],4:[['R','B']],5:[['L','T'],['R','B']],6:[['T','B']],7:[['L','B']],8:[['B','L']],9:[['T','B']],10:[['T','R'],['B','L']],11:[['R','B']],12:[['R','L']],13:[['T','R']],14:[['L','T']]};
  function edgePoint(edge,i,j,tl,tr,br,bl,cw,ch){var t;if(edge==='T'){t=clampt(tl/(tl-tr));return [(i+t)*cw,j*ch];}if(edge==='R'){t=clampt(tr/(tr-br));return [(i+1)*cw,(j+t)*ch];}if(edge==='B'){t=clampt(br/(br-bl));return [(i+1-t)*cw,(j+1)*ch];}t=clampt(bl/(bl-tl));return [i*cw,(j+1-t)*ch];}
  function drawGridLines(){ctx.save();ctx.strokeStyle='rgba(10,10,10,0.09)';ctx.lineWidth=1;var N=10,i,p;for(i=1;i<N;i++){p=i/N;ctx.beginPath();ctx.moveTo(p*W,0);ctx.lineTo(p*W,H);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p*H);ctx.lineTo(W,p*H);ctx.stroke();}ctx.restore();}
  function drawContour(grid,gridN){var stride=gridN+1,cw=W/gridN,ch=H/gridN,i,j,tl,tr,br,bl,c,segs,k,a,b;ctx.save();ctx.strokeStyle=INK;ctx.lineWidth=3.5;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();for(j=0;j<gridN;j++){for(i=0;i<gridN;i++){tl=grid[j*stride+i];tr=grid[j*stride+i+1];br=grid[(j+1)*stride+i+1];bl=grid[(j+1)*stride+i];c=0;if(tl>0)c|=1;if(tr>0)c|=2;if(br>0)c|=4;if(bl>0)c|=8;segs=MS[c];if(!segs||!segs.length)continue;for(k=0;k<segs.length;k++){a=edgePoint(segs[k][0],i,j,tl,tr,br,bl,cw,ch);b=edgePoint(segs[k][1],i,j,tl,tr,br,bl,cw,ch);ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);}}}ctx.stroke();ctx.restore();}
  function drawPoints(){var i,p,px,py,s;for(i=0;i<points.length;i++){p=points[i];px=p.x*W;py=p.y*H;if(p.label===0){s=12;ctx.fillStyle=PAPER;ctx.fillRect(px-s/2-2.5,py-s/2-2.5,s+5,s+5);ctx.fillStyle=INK;ctx.fillRect(px-s/2,py-s/2,s,s);}else{ctx.fillStyle=PAPER;ctx.beginPath();ctx.arc(px,py,8.5,0,6.2832);ctx.fill();ctx.beginPath();ctx.arc(px,py,6.5,0,6.2832);ctx.fillStyle=SIGNAL;ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=INK;ctx.stroke();}}}
  function draw(grid,gridN){ctx.clearRect(0,0,W,H);ctx.fillStyle=PAPER;ctx.fillRect(0,0,W,H);if(grid){var cw=W/gridN,ch=H/gridN,stride=gridN+1,i,j,avg;for(j=0;j<gridN;j++){for(i=0;i<gridN;i++){avg=grid[j*stride+i]+grid[j*stride+i+1]+grid[(j+1)*stride+i]+grid[(j+1)*stride+i+1];ctx.fillStyle=avg>0?'rgba(255,77,0,0.15)':'rgba(10,10,10,0.05)';ctx.fillRect(i*cw,j*ch,cw+1,ch+1);}}}drawGridLines();if(grid)drawContour(grid,gridN);drawPoints();}

  function accuracyOf(scorer){var c=0,i,p,pred;for(i=0;i<points.length;i++){p=points[i];pred=scorer(p.x,p.y)>0?1:0;if(pred===p.label)c++;}return points.length?c/points.length:0;}
  function splitCount(){var n1=0,i;for(i=0;i<points.length;i++)if(points[i].label===1)n1++;return [points.length-n1,n1];}
  function finalStats(scorer,extra){var sc=splitCount();setText('s-model',MODEL_LABEL[state.algo]);setText('s-points',String(points.length));setText('s-split',sc[0]+' / '+sc[1]);if(sc[0]===0||sc[1]===0)setText('s-acc','100%');else setText('s-acc',Math.round(accuracyOf(scorer)*100)+'%');if(extra){setText('s-xlabel',extra.l);setText('s-x',extra.v);}}

  function settle(scorer,token,extra){if(token!==animToken)return;var grid=vertexScores(GRID_FINAL,scorer);cachedGrid=grid;cachedN=GRID_FINAL;draw(grid,GRID_FINAL);finalStats(scorer,extra);}
  function runTree(token,animate){var i,idx=[];for(i=0;i<points.length;i++)idx.push(i);var root=buildTree(idx,0,state.params.treeDepth),maxD=treeMaxDepth(root),leaves=treeLeaves(root);var extra={l:'DEPTH / LEAVES',v:maxD+' / '+leaves};if(!animate||maxD<=0){settle(treeScorer(root,maxD+1),token,extra);return;}var reveal=1;(function frame(){if(token!==animToken)return;var grid=vertexScores(GRID_ANIM,treeScorer(root,reveal));cachedGrid=grid;cachedN=GRID_ANIM;draw(grid,GRID_ANIM);setText('s-xlabel','DEPTH / LEAVES');setText('s-x','GROW D'+reveal);if(reveal>=maxD){settle(treeScorer(root,maxD+1),token,extra);return;}reveal++;requestAnimationFrame(frame);})();}
  function runLogreg(token,animate){var w=[0,0,0],lr=state.params.lr,EPOCHS=500,e;if(!animate){for(e=0;e<EPOCHS;e++)logregEpoch(w,lr);settle(logregScorer(w),token,{l:'EPOCHS / LOSS',v:EPOCHS+' · '+logregLoss(w).toFixed(3)});return;}e=0;(function frame(){if(token!==animToken)return;var k;for(k=0;k<14&&e<EPOCHS;k++){logregEpoch(w,lr);e++;}var grid=vertexScores(GRID_ANIM,logregScorer(w));cachedGrid=grid;cachedN=GRID_ANIM;draw(grid,GRID_ANIM);setText('s-xlabel','EPOCHS / LOSS');setText('s-x','EPOCH '+e);if(e>=EPOCHS){settle(logregScorer(w),token,{l:'EPOCHS / LOSS',v:e+' · '+logregLoss(w).toFixed(3)});return;}requestAnimationFrame(frame);})();}
  function runSVM(token,animate){var C=state.params.svmC,lambda=1/(2*C),K=svmKfun(),m={alpha:[],t:1},i;for(i=0;i<points.length;i++)m.alpha.push(0);var ITERS=Math.max(1500,points.length*40),kname=state.params.svmKernel.toUpperCase();if(!animate){svmStep(m,lambda,K,ITERS);settle(svmScorer(m,lambda,K),token,{l:'KERNEL / ITERS',v:kname+' · '+ITERS});return;}var done=0,per=Math.max(40,(ITERS/40)|0);(function frame(){if(token!==animToken)return;var chunk=Math.min(per,ITERS-done);svmStep(m,lambda,K,chunk);done+=chunk;var grid=vertexScores(GRID_ANIM,svmScorer(m,lambda,K));cachedGrid=grid;cachedN=GRID_ANIM;draw(grid,GRID_ANIM);setText('s-xlabel','KERNEL / ITERS');setText('s-x',kname+' · '+done);if(done>=ITERS){settle(svmScorer(m,lambda,K),token,{l:'KERNEL / ITERS',v:kname+' · '+ITERS});return;}requestAnimationFrame(frame);})();}

  function recompute(animate){animToken++;var token=animToken;updateEmpty();var n=points.length;if(n===0){cachedGrid=null;draw(null,GRID_FINAL);setText('s-model',MODEL_LABEL[state.algo]);setText('s-points','0');setText('s-split','0 / 0');setText('s-acc','—');setText('s-xlabel','STATUS');setText('s-x','EMPTY');return;}var sc=splitCount();if(sc[0]===0||sc[1]===0){var val=sc[1]>0?1:-1;settle(function(){return val;},token,{l:'STATUS',v:'ONE CLASS'});return;}if(state.algo==='knn')settle(knnScorer(),token,{l:'NEIGHBORS (K)',v:String(Math.min(state.params.knnK,n))});else if(state.algo==='tree')runTree(token,animate);else if(state.algo==='logreg')runLogreg(token,animate);else if(state.algo==='svm')runSVM(token,animate);}
  function previewCompute(){if(rafPending)return;rafPending=true;requestAnimationFrame(function(){rafPending=false;recompute(false);});}

  function sizeCanvas(){var rect=canvas.getBoundingClientRect();if(rect.width===0)return;dpr=Math.min(2,window.devicePixelRatio||1);W=rect.width;H=rect.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw(cachedGrid,cachedN);}
  function updateEmpty(){emptyEl.style.display=points.length?'none':'flex';}

  var drawing=false,lastAdd=null;
  function toData(ev){var r=canvas.getBoundingClientRect();return {x:clamp01((ev.clientX-r.left)/r.width),y:clamp01((ev.clientY-r.top)/r.height)};}
  function addPoint(d){if(points.length>=MAXPTS)return;points.push({x:d.x,y:d.y,label:state.brush});}
  canvas.addEventListener('pointerdown',function(ev){ev.preventDefault();try{canvas.setPointerCapture(ev.pointerId);}catch(e){}drawing=true;var d=toData(ev);addPoint(d);lastAdd=d;updateEmpty();draw(cachedGrid,cachedN);});
  canvas.addEventListener('pointermove',function(ev){if(!drawing)return;var d=toData(ev);if(!lastAdd||dist(d,lastAdd)>0.035){addPoint(d);lastAdd=d;draw(cachedGrid,cachedN);}});
  window.addEventListener('pointerup',function(){if(!drawing)return;drawing=false;recompute(true);});

  function updateParamVisibility(){var groups=document.querySelectorAll('.pgroup'),i;for(i=0;i<groups.length;i++)groups[i].classList.toggle('show',groups[i].getAttribute('data-for')===state.algo);var gc=document.getElementById('ctl-gamma');if(gc)gc.style.display=state.params.svmKernel==='rbf'?'':'none';}
  function setActive(sel,el){var list=document.querySelectorAll(sel),i;for(i=0;i<list.length;i++)list[i].classList.remove('active');el.classList.add('active');}
  function bind(){var algos=document.querySelectorAll('.algo-btn'),i;for(i=0;i<algos.length;i++)algos[i].addEventListener('click',function(){state.algo=this.getAttribute('data-algo');setActive('.algo-btn',this);updateParamVisibility();recompute(true);});var brushes=document.querySelectorAll('.brush-btn');for(i=0;i<brushes.length;i++)brushes[i].addEventListener('click',function(){state.brush=parseInt(this.getAttribute('data-brush'),10);setActive('.brush-btn',this);});var kernels=document.querySelectorAll('.kernel-btn');for(i=0;i<kernels.length;i++)kernels[i].addEventListener('click',function(){state.params.svmKernel=this.getAttribute('data-kernel');setActive('.kernel-btn',this);updateParamVisibility();recompute(true);});var lr=document.getElementById('lr');lr.addEventListener('input',function(){state.params.lr=parseInt(this.value,10)/100;setText('lrv',state.params.lr.toFixed(2));previewCompute();});var knnK=document.getElementById('knnK');knnK.addEventListener('input',function(){state.params.knnK=parseInt(this.value,10);setText('knnKv',String(state.params.knnK));previewCompute();});var gamma=document.getElementById('svmGamma');gamma.addEventListener('input',function(){state.params.svmGamma=parseInt(this.value,10);setText('svmGammav',String(state.params.svmGamma));previewCompute();});var cc=document.getElementById('svmC');cc.addEventListener('input',function(){state.params.svmC=parseInt(this.value,10);setText('svmCv',String(state.params.svmC));previewCompute();});var td=document.getElementById('treeDepth');td.addEventListener('input',function(){state.params.treeDepth=parseInt(this.value,10);setText('treeDepthv',String(state.params.treeDepth));previewCompute();});document.getElementById('btn-random').addEventListener('click',function(){patternIdx=(patternIdx+1)%PATTERNS.length;points=generate(PATTERNS[patternIdx]);updateEmpty();recompute(true);});document.getElementById('btn-clear').addEventListener('click',function(){points=[];updateEmpty();recompute(false);});}
  function syncOutputs(){setText('lrv',state.params.lr.toFixed(2));setText('knnKv',String(state.params.knnK));setText('svmGammav',String(state.params.svmGamma));setText('svmCv',String(state.params.svmC));setText('treeDepthv',String(state.params.treeDepth));}
  function start(){syncOutputs();updateParamVisibility();bind();points=generate('moons');updateEmpty();var ro=new ResizeObserver(function(){sizeCanvas();if(!inited&&W>0){inited=true;recompute(false);}});ro.observe(canvas);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
