/**
 * Reads/writes the generated-projects manifest and regenerates the
 * `src/data/generatedProjects.ts` module that `data.tsx` consumes.
 *
 * The TS module is fully machine-owned — never hand-edit it. Each project's
 * screenshot is imported statically so next/image keeps its blur placeholder,
 * exactly like the curated portfolio items.
 */
import fs from 'node:fs';

import {config, ProjectRecord} from './config';

export function readManifest(): ProjectRecord[] {
  if (!fs.existsSync(config.manifestPath)) return [];
  const raw = fs.readFileSync(config.manifestPath, 'utf8').trim();
  if (!raw) return [];
  return JSON.parse(raw) as ProjectRecord[];
}

export function writeManifest(records: ProjectRecord[]): void {
  fs.writeFileSync(config.manifestPath, `${JSON.stringify(records, null, 2)}\n`, 'utf8');
}

/** A valid TS identifier derived from a slug, e.g. "todo-heatmap" -> "gen_todo_heatmap". */
function importName(slug: string): string {
  return `gen_${slug.replace(/[^a-zA-Z0-9]+/g, '_')}`;
}

/** Regenerate the TS module from the manifest. Newest projects first. */
export function regenerateModule(records: ProjectRecord[]): void {
  const ordered = [...records].sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  // Import statements must satisfy simple-import-sort: parent (`../`) imports,
  // sorted alphabetically by path, come before the sibling (`./dataDef`) import.
  const imageImports = [...records]
    .sort((a, b) => a.image.localeCompare(b.image))
    .map(r => `import ${importName(r.slug)} from '../images/portfolio/${r.image}';`)
    .join('\n');
  const imports = imageImports ? `${imageImports}\nimport type {PortfolioItem} from './dataDef';` : '';

  const items = ordered
    .map(r => {
      const title = JSON.stringify(r.title);
      const description = JSON.stringify(r.description);
      const url = JSON.stringify(r.url);
      const sourceUrl = JSON.stringify(r.sourceUrl);
      return `  {\n    title: ${title},\n    description: ${description},\n    url: ${url},\n    sourceUrl: ${sourceUrl},\n    image: ${importName(
        r.slug,
      )},\n  },`;
    })
    .join('\n');

  const importBlock = imports || `import type {PortfolioItem} from './dataDef';`;

  const body = `/**
 * AUTO-GENERATED by scripts/generate-project — do not edit by hand.
 * Each entry is a Claude-generated demo deployed to Cloud Run.
 */
${importBlock}

export const generatedProjects: PortfolioItem[] = [
${items}
];
`;

  fs.writeFileSync(config.generatedModulePath, body, 'utf8');
}
