/**
 * AUTO-GENERATED by scripts/generate-project — do not edit by hand.
 * Each entry is a Claude-generated demo deployed to Cloud Run.
 */
import gen_price_paths from '../images/portfolio/generated-price-paths.png';
import type {PortfolioItem} from './dataDef';

export const generatedProjects: PortfolioItem[] = [
  {
    title: "Price Path Explorer",
    description: "Interactive Monte Carlo simulator showing how market volatility affects possible asset price futures.",
    url: "https://demo-price-paths-gsjoa373ca-nw.a.run.app",
    image: gen_price_paths,
  },
];
