/**
 * AUTO-GENERATED by scripts/generate-project — do not edit by hand.
 * Each entry is a Claude-generated demo deployed to Cloud Run.
 */
import type {PortfolioItem} from './dataDef';

export const generatedProjects: PortfolioItem[] = [
];
